### ISSUE TITLE
ProGuardRules如何使用？

### ISSUE THREAD

**Issue by hnty545** [wangtotang/ProGuardRules#1]
您好，gradle依赖的方式如何使用，怎么知道依赖的库有哪些pro？
我查看了libs并没有发现.pro文件，我如何在appmodule中include

**Comment by fenjueai** [comment]
buildTypes {
        release {
            consumerProguardFiles fileTree(dir: 'rules', include: ['*.pro']).asList().toArray()
        }
    }
你在librarymodule中添加以上，rules改成自己的名称，欢迎一起交流学习和更新

**Comment by hnty545** [comment]
consumerProguardFiles 方式会默认应用所有混淆配置吗？
如何只是引入文件，我的module能够看到这些文件，根据需要应用呢

**Comment by fenjueai** [comment]
是的，默认应用所有配置。
我想可以放在assets目录下，可以看得到吧？

**Comment by hnty545** [comment]
对，可能要放到assets，然后根据需要引入，但是有确定，会跟随打包到app里吧

**Comment by hnty545** [comment]
这种依赖的方式不可行，proguard配置文件只支持本地绝对路径，依赖进来以后aar包的位置不固定层级也很多，没什么可用性。
只能当文件拷贝进appmodule来用了
